version: '3.8'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=gymapi
      - POSTGRESQL_PASSWORD=gymapi321
      - POSTGRESQL_DATABASE=gymapidb